# -*- coding: utf-8 -*-
"""Day 06 Generative AI Prompt Eng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XloNgahxQLG-WNyGWGyfdbq9XWfIHuHY
"""

from transformers import pipeline

classifier=pipeline("sentiment-analysis",
                    model="distilbert-base-uncased-finetuned-sst-2-english")

text=input("Enter a text to Analyse:")
result=classifier(text)
print(result)

"""Example 2 - Text Generation (GPT-2)"""

from transformers import pipeline

generator = pipeline("text-generation",model="gpt2")
prompt="In a future where healthcare is fully decentralized"
outputs=generator(prompt,max_new_tokens=80,do_sample=True,temperature=0.5,
                  top_p=0.9,num_return_sequences=0)

for i,out in enumerate(outputs):
  print(f"--- generated {i} ---")
  print(out['generated_text'])

"""USING API TOKENS"""

pip install -q langchain-groq

pip install -q langchain-core

pip install -q langchain langchain-core langchain-groq

pip install -q langchain

from getpass import getpass
import os
HF_TOKEN=getpass("Enter your Hugging Face Token:")
os.environ["HF_TOKEN"]=HF_TOKEN

from huggingface_hub import  InferenceClient
MODEL_ID="meta-llama/Meta-Llama-3-8B-Instruct"
client=InferenceClient(token=HE_TOKEN,model=MODEL_ID)
def extract_text(resp):
  try:
    return resp.choices[0].message.content
  except Exception:
    try:
      return resp['choices'][0]['message']['content']
    except :
      return str(resp)
messages=[
    {"role":"system","content":"You are a helpful Leetcode solver."},
    {"role":"user","content":"Explain Two sum problem with eg."}
]
resp=client.chat_completion(messages=messages,max_tokens=400)
print(extract_text(resp))

pip install -q langchain-groq

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROO_API_KEY"] = "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"

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)


prompt = PromptTemplate(
    input_variables=["instruction"],
    template="follow the instruction and provides the output clearly:\n\nInstruction:{instruction}\n\nAnswer:"
)

parser = StrOutputParser()
chain = prompt | llm | parser
chain.invoke({"instruction":"Explain Two sum problem with eg."})

