# -*- coding: utf-8 -*-
"""Day 07 Embedded system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQo7Fo5bPZOkxmEAXN5v8N4-XhRrb7hP
"""

# Consolidate all installations and fix transformer version
# Install chromadb and sentence-transformers
!pip install chromadb sentence-transformers --quiet

# Install llama-index and its specific integrations
!pip install llama-index llama-index-llms-groq llama-index-embeddings-huggingface --quiet

# Downgrade transformers to a compatible version and reinstall sentence-transformers
# The function 'merge_with_config_defaults' was removed in transformers 4.38.0
# Downgrading to 4.37.2 is a known fix for this specific ImportError and compatibility issues.
# The --force-reinstall ensures that the packages are reinstalled even if they exist.
!pip install transformers==4.37.2 sentence-transformers --force-reinstall --quiet

print("All necessary packages installed and transformers version adjusted. Please restart the runtime.")

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
import chromadb

print(f"chromadb version: {chromadb.__version__}")

documents=[
    "Hi How are you",
    "Vimal is Srivar",
    "Srivar is mode of transpotation for vimal",
    "Srivar is used to query vimal",
    "Srivar trains the model of vimal"
]

query_keyword = "srivar"

print("="*45)

query_keyword = "vehicle"
print("=" * 60)
print(f"Keyword: {query_keyword}")
print("=" * 60)
for i, doc in enumerate(documents):
  if query_keyword.lower() in doc.lower():
    print(f" Found [doc_{i}]: {doc}")
  else:
    print(f" Missed [doc_{i}]: {doc}")
print()
print("problem : doc_2 talks about 'Cars and Trucks' - which are vehicles !")
print("But Keyword Search Missed it because it searched for the exact word vehicle")

!pip install llama-index llama-index-llms-groq sentence-transformers --q

!pip install llama-index-embeddings-huggingface --q

import os
from textwrap import dedent

os.makedirs("data",exist_ok=True)

file_path = "data/v.txt"

content =  dedent("""
Empowering Tomorrow's Decisions with Data Science

Data Science is instrumental in extracting valuable insights from vast datasets, guiding informed decision-making, and fueling innovation across industries. By leveraging advanced analytics and machine learning techniques, Data Science empowers organizations to unlock the full potential of their data, driving growth, efficiency, and competitive advantage in the digital age.
ABOUT CoE

Welcome to the Centre for Data Science, where data meets discovery. Our collaborative hub pioneers research, education, and industry partnerships to advance the frontiers of data analytics and machine learning. Through cutting-edge methodologies, interdisciplinary collaborations, and experiential learning, we’re shaping the future of data-driven decision-making and empowering the next generation of data scientists and analysts. Join us as we unravel the mysteries hidden within the data and pave the way for a smarter, more informed future.
OBJECTIVES

Provide training programs with globally recognized certifications encompassing various aspects of Data Science, including data analysis, machine learning and statistical modeling.

Conduct hands-on projects and organize hackathon to furnish students with real-world experience in implementing data science methodologies and techniques.

Support research endeavors and patent applications to propel innovation and contribute to the progression of data science technologies, with a focus on crafting proprietary solutions.

Extend consultancy services to industry partners in search of expert guidance in data science, furnishing tailored solutions and recommendations to address specific data challenges and fortify organizational analytics capabilities.

Offer guidance and resources to students aspiring to pursue careers in data science, providing internships, and industry collaborations to nurture their professional growth.

CENTRE HEAD

Ms. Parvathy K, Assistant Professor/AIDS
CENTRE COORDINATORS

Ms.G.Durga Devi, Assistant Professor/AIDS
EVENTS

S.No	Name of the Event	Resource Person
Date
1	Mastering in MLO ps	Mr. C.B. Veerakumar, Associate Engineering Analyst, Wipro Technologies	02.07.25–18.07.25
2	Introduction to Data Bricks	Ms. K. Parvathy, AP/AI&DS	03.05.25
3	Fundamentals of Generative AI	Ms. K. Parvathy, AP/AI&DS	29.04.25
4	Hand-on Session on Exploratory Data Analysis	Ms. K. Parvathy, AP/AI&DS	05.04.25
5	Basics of Business Intelligence	Ms. K. Parvathy, AP/AI&DS	05.04.25
6	Data Visualization Tools and Techniques	Ms. K. Parvathy, AP/AI&DS	15.03.25
7	Hands-on Session on Power BI	Ms. K. Parvathy, AP/AI&DS	15.02.25
8	Introduction to Data Visualization	Ms.K.Parvathy, AP/AI&DS	28.12.2024
9	Data Visualization using Power BI	Ms. Ramalakshmi, IV AIDS	30.11.2024
10	(FN) Hand on Data Analytics using Excel Worksheets	Mr. M. Sangarapandian & Mr. N. Sri Harikrishna, III AIDS B	23.11.2024
11	(AN) Hands on Data Analytics and Visualization using Orange	Mr. M. Sangarapandian & Mr. N. Sri Harikrishna, III AIDS B	23.11.2024
12	Innovative Roadmap of Data Science	Gokul C, Likith Kumar, IV AI&DS	09.11.2024
13	Open for Innovation KNIME - Overview of KNIME Software	Mr.Sangarapandian and Mr.Yaswanth Saran Sundar, III AI&DS	26.10.2024
14	Data Science in Action: Mastering Innovation Through Hands-On Learning	Mr Shreenivasan S N, Data Analyst, LatentView Analytics	19.10.2024
15	(FN) Innovating with Data Science Foundations	Mr.Sangarapandian and Mr.Yaswanth Saran Sundar, SECE	05.10.2024
16	(AN) Evolution of GenAI on Cloud Platform	Mr.Aashu Dev, AWS Certified Trainer, AWS Academy	05.10.2024
17	Innovative Feature Engineering Demystified: Transforming Data with Python for Cutting-Edge Solutions	Ms. Bhuvaneswari, Corporate Trainer and Mentor, Imarticus Learning	14.09.2024
18	Mastering Data Science Basics: A Practical Approach to Data Loading, Cleaning, and Visualization	Mr.C.B.Veerakumar, Associate Engineering Analyst, Wipro Technologies	31.08.2024
19	Data Science	Mr.G.Rajesh Mani Kumar, Solution Engineer, Proximus, Brussels, Belgium	24.08.2024
20	Data Science Bootcamp: Mastering Data from Wrangling to Visualization	Mr.S.Manikandan, Director, Geons Logix Pvt Ltd	29.07.2024 to 14.08.2024
21	Data Science in Practice: Real-world Applications and Case Studies	Mr.Ramkumar I, Project Manager, Cognizant Technologies	25.05.2024
22	Data Visualization Using Power BI	Dr. M. Nivaashini	11.05.2024
23	Mastering Data Science: Techniques for Analysis and Interpretation	Mr. Gokulakrishnan M, Project Associate, IIT Madras	27.04.2024
24	The Power of Data: Empowering Decision Making with Data Science	Dr.M.Lakshmi, AP/AIDS	19.04.2024
25	Data-driven Discovery using Tableau	Dr.M.Lakshmi, AP/AIDS	09.03.2024
26	Cracking the Data Code: Essential Principles of Data Science	Dr.M.Lakshmi, AP/AIDS	24.02.2024
""").strip()

with open(file_path,"w",encoding="utf-8") as f:
    f.write(content)
print(f"created file:{file_path}(len{content.splitlines()})")

!pip uninstall -y transformers sentence-transformers llama-index llama-index-core \
llama-index-llms-groq llama-index-embeddings-huggingface peft accelerate

!pip install transformers==4.41.2
!pip install sentence-transformers==3.0.1
!pip install accelerate==0.31.0
!pip install peft==0.11.1

!pip install llama-index
!pip install llama-index-llms-groq
!pip install llama-index-embeddings-huggingface

import os
from llama_index.llms.groq import Groq
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

os.environ["GROQ_API_KEY"] = "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"

llm = Groq(model="llama-3.1-8b-instant")

embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

file_path = "data/v.txt"

documents = SimpleDirectoryReader(input_files=[file_path]).load_data()

index = VectorStoreIndex.from_documents(documents,embed_model=embed_model)

query_engine = index.as_query_engine(llm=llm)

response = query_engine.query(
    "Summarize the content of the documents in 3 bullet points:"
)

print(response.response)

# Reinstall sentence-transformers and transformers to resolve potential dependency conflicts
!pip install sentence-transformers transformers --upgrade --quiet
print("Reinstallation of sentence-transformers and transformers completed. Please re-run the previous cell.")

print("Loading embedding model...(may take 1-2 min on first run)")
model=SentenceTransformer('all-MiniLM-L6-v2')
print("Embedding model loaded successfully")
print(f"model produces vectors of size:{model.get_sentence_embedding_dimension()}dimensions")

sentence = [
    "ETL is used to clean and transform data",
    "Data transform is a key pipeline step",
    "The sky is blue and clouds are white",
]

embedding = model.encode(sentences)

print(f"Number of sentences:{len(sentences)}")
print(f"Shape of embedding array: {embeddings.shape}")

print()

def cosine_similarity(vac_a,vac_b):
  dot_product


print("COSINE SIMILARITY SCORE")
print("=", 60)
print(f"Sentence 0:'{sentence[0]}'")
print(f"Sentence 1: '{sentence[1]}'")
print(f"Sentence 2: '{sentence[2]}'")
print()