# -*- coding: utf-8 -*-
"""Day 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnF-4k9pvmB38-191PBcWFxjPsC0CxiX
"""

!pip install sentence-transformers chromadb groq pandas -q

import pandas as pd
import chromadb

from sentence_transformers import SentenceTransformer
from groq import Groq
import os

print("all installed")

GROQ_API_KEY = "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"
os.environ["GROQ_API_KEY"]=GROQ_API_KEY
groq_client=Groq(api_key=Groq)
print("Success")

df=pd.read_csv('college_notes.csv')
print("Shape of dataset: ",df.shape)
print("\nCoulmn names:",df.columns.tolist())
print("\nfirst 3 rows:")
print(df.head(3))

print("Subjects in dataset:")
print(df['subject'].value_counts())

print("\nSample of topics")
print(df[['note_id','subject','topic']].to_string(index=False))
print("\nLength of content (number of characters) for each note:")
df['content_length']=df['content'].apply(len)
print(df[['topic','content_length']].to_string(index=False))

documents = df['content'].tolist()
ids=[f"note_{row['note_id']}" for row in df.to_dict("records")]
metadatas=[
    {"subject" : row["subject"], "topic": row["topic"]}
    for row in df.to_dict("records")
]
print(f"Total chunk prepared:{len(documents)}")
print(f"First document ID:{ids[0]}")
print(f"First document metadata:{metadatas[0]}")
print(f"First 100 characters of first document:\n{documents[0][:100]}")

print("Subsequent runs will be faster as the model is cached")
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

print("\nEmbedding model loaded successfully.")
test_embedding = embedding_model.encode("This is a test sentence.")
print(f"Test embedding shape:{test_embedding.shape}")
print(f"First 5 values of test embedding; {test_embedding[:5]}")

chroma_client=chromadb.Client()
collection=chroma_client.create_collection(name="college_notes")
print("ChromaDb client created")
print(f"Collection name:college_notes_rag")
print(f"Documents in collection so far:{collection.count()}")

print("Generating embedding for all 15 notes...")
print("this may take 15-30 sec")
embeddings = embedding_model.encode(documents,show_progress_bar=True)
print(f"Embedding matrix shape: {embeddings.shape}")
embedding_list=embeddings.tolist()
collection.add(
    documents=documents,
    metadatas=metadatas,
    ids=ids,
    embeddings=embedding_list
)
print(f"\nDocument successfully added to the collection")
print(f"Document in collection now:{collection.count()}")

def retrieve_relevant_chunks(question,top_k=3):
      print("Retrieving relevant chunks...")
      question_embedding=embedding_model.encode(question).tolist()
      results=collection.query(
      query_embeddings=[question_embedding],
      n_results=top_k
      )
      return results

test_question="what if etl and how it works?"
print(f"Test Question:{test_question}")
print("="*70)
results=retrieve_relevant_chunks(test_question,top_k=3)

print("\nTop 3 Retrieved chunks")
print("="*70)

for i,(doc,dist,meta) in enumerate(zip(
    results['documents'][0],
    results['distances'][0],
    results['metadatas'][0]
 )):
      print(f"\nResult {i+1}:")
      print(f" Subject :{meta['subject']}")
      print(f" Topic :{meta['topic']}")
      print(f" Distance :{dist:.4f}")
      print(f" Content : {doc[:120]}")

context_parts = []

for 1, (doc,meta) in enumerate(zip(
    results['documents'][0],
    results['metadatas'][0]
)):
    chunk_text = f"[]"

temperature = 0.1
max_tokens=500

def ask_college_assistant(question,top_k=3,verbose=True):
  if verbose:
    print(f"Qusetion :{question}")
    print("="*60)
    print("Step 1 : Retrieving relevant document...")
  results=retrieve_relevant_chunks(question,top_k=top_k)
  if verbose:
    print(f"Retrieved {top_k} chunk from the knowledge base:")
    print("\nstep3 : Sending to LLM for answer generation...")

    answer = generate_rag_answer(question, context)

    if verbose:
      print("\n"+"="*60)
      print("Answer:")
      print("="*60)
      print(answer)
      print("="*60)

    return answer

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ['GROQ_API_KEY']="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"
llm=ChatGroq(model="llama-3.3-70b-versatile",temperature=0)
prompt=PromptTemplate(
    imput_variables=["instruction"],
    template="follow the instruction and provide the output clearly:\n\nInstruction:{instruction}"

)
parser=StrOutputParser()
chain=prompt | llm | parser
response=chain.invoke({
    "instruction":""
})
print("\nZero-shot output:\n",response)