# -*- coding: utf-8 -*-
"""Day 4 BigData Pyspark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ger3veBGGCBU6C-rxVS6FwI_0IPImQHV
"""

!pip install pyspark --quiet
print('Pyspark installation completed')

"""cell 2 - import Pyspark modules and create sparksession

"""

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import year,month, to_date,col,round as spark_round


import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

#create sparksession
spark = SparkSession.builder \
  .appName('Day 4 BigData Sales')\
  .config('spark.sql.adaptive.enable','true')\
  .getOrCreate()

print(f'Spark version : {spark.version}')
print(f'SparkSession : ACTIVE')

!pip install pyspark --quiet
print('Pyspark installation completed')

"""Bronze

"""

df_Bronze=spark.read\
  .option('header','true')\
  .option('inferSchema','true')\
  .csv('large_sales_data.csv')

print('=== Bronze layer -- Raw Data ===')
print(f'Rows   : {df_Bronze.count()}')
print(f'Columns: {len(df_Bronze.columns)}')
print(f'Names  : {df_Bronze.columns}')
print()
df_Bronze.printSchema()

print("Firs 5 rows:")
df_Bronze.show(5,truncate=False)
print("\nBasics statistics for numeric columns:")
df_Bronze.select('quantity','unit_price','revenue').describe().show()

from os.path import isfile
df_Bronze.write\
   .mode('overwrite')\
   .parquet('sales_bronze.parquet')
print('Bronze paruet saved: sales_bronze.parquet')
import os
def get_dir_size(path):
  if os.path.isfile(path):
    return os.path.getsize(path)/1024
  total =0
  for dirpath, dirnames, filenames in os.walk(path):
    for f in filenames:
      fp = os.path.join(dirpath, f)
      total += os.path.getsize(os.path.join (dirpath, f))
  return total/1024
csv_size = get_dir_size('large_sales_data.csv')
parquet_size = get_dir_size('sales_bronze.parquet')
reduction=(1-parquet_size/csv_size)*100
print(f'CSV size: {csv_size:.1f} KB')
print(f'Parquet size: {parquet_size:.1f} KB')
print(f'Reduction   : {reduction:.1f}%smaller')
print(f'\nAt 1 TB scale: CSV=1000 GB -> parquet={1000*(1-reduction/100):.0f} GB')

"""# cell 6 Silver

"""

df_silver = df_Bronze \
   .dropDuplicates() \
   .dropna(subset=['order_id','product','revenue'])

df_silver=df_silver.withColumn(
    'order_date',
    to_date(col('order_date'),'yyyy-MM--dd')
)

df_silver=df_silver \
    .withColumn('order_year', year(col('order_date'))) \
    .withColumn('order_month', month(col('order_date')))

df_silver=df_silver.withColumn(
    'revenue_category',
    F.when(col('revenue')>40000, 'High')
    .when(col('revenue')>10000, 'Medium')
    .otherwise('Low')
)

print(f'Silver Layer rows: {df_silver.count()}')
print(f'New columns added : order_year, order_month, revenue_category')
df_silver.select('product','revenue','order_year','order_month','revenue_category')



