# -*- coding: utf-8 -*-
"""Day 5 MachineLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VofCXQuIVzZqRvDy99DVnDnsY_sHn2xi
"""

!pip install twilio --quiet

import os
from getpass import getpass
from twilio.rest import Client

# --- Twilio credentials ---
TW_SID = os.environ.get('TWILIO_SID')
TW_TOKEN = os.environ.get('TWILIO_TOKEN')


if not TW_SID or not TW_TOKEN:
    print("Enter your Twilio Account SID and Auth Token:")
    TW_SID = getpass("Twilio SID: ")
    TW_TOKEN = getpass("Twilio Token: ")
    os.environ['TWILIO_SID'] = TW_SID
    os.environ['TWILIO_TOKEN'] = TW_TOKEN

FROM ='whatsapp:+14155238886'

TO=input("enter ur phone no:").strip()
if not TO.startswith('whatsapp:'):
       TO=f'whatsapp:{TO}'
client=Client(TW_SID,TW_TOKEN)

msg=client.messages.create(
    body='hello from twilio whatsapp sandbox-text message',
    from_=FROM,to=TO
)
print("Message sent successfully")
print("message SID:",msg.sid)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

print("all librraries imported")

df_ml = df.copy()
le_gender = LableEncoder()
df_ml['gender_encoded']=le_gender.fit_transform(df_ml['gender'])
print(f'Gender encoding: {dict(zip(le_gender.classes_, le_gender.transform(le_gende.classes_)))}')

le_dept = LableEncoder()
df_ml['department_encoded']=le_dept.fit_transform(df_ml['department'])

print(f'Department encoding : {dict(zip(le_dept.classes_, le_dept.transform(le_dept.classes_)))}')

df = pd.DataFrame({
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'department': ['HR', 'IT', 'Finance', 'HR', 'IT'],
    'age': [25, 30, 35, 28, 40]
}) # Sample DataFrame for demonstration
df_ml=df.copy()
le_gender=LabelEncoder()
df_ml['gender_encoded']=le_gender.fit_transform(df_ml['gender'])
print(f"Gender encoding:{dict(zip(le_gender.classes_,le_gender.transform(le_gender.classes_)))}")
le_dept=LabelEncoder()
df_ml['dept_encoded']=le_dept.fit_transform(df_ml['department'])
print(f"Department encoding:{dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))}")
print('\nNew columns added:gender_encoded,department_encoded')
df_ml[['gender','gender_encoded','department','dept_encoded']].head(5)

